### ISSUE TITLE
Sort Function Problems

### ISSUE THREAD

**Issue by borissov** [tureki/php-closure-compiler#2]
I use this wrapper for closure compiler, but SORT function is realy bad think.
Sort function exchange params for closure and sometimes move jquery after libraries who use it....

**Comment by jacobalberty** [comment]
Borissov see my pull request #1 it allows you to add a 'sort' => false key to the array you use to construct which will disable the sort function.

**Comment by borissov** [comment]
Thank you!

**Comment by tureki** [comment]
This issue have been fixed in  [v1.0.5](https://github.com/tureki/php-closure-compiler/releases/tag/v1.0.5) version :+1:
